# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='lth_egm.proto',
  package='lth.egm',
  serialized_pb='\n\rlth_egm.proto\x12\x07lth.egm\"\xd0\x02\n\x06Header\x12\r\n\x05seqno\x18\x01 \x01(\r\x12\n\n\x02tm\x18\x02 \x01(\r\x12=\n\x05mtype\x18\x03 \x01(\x0e\x32\x1b.lth.egm.Header.MessageType:\x11MSGTYPE_UNDEFINED\x12<\n\x04mode\x18\x04 \x01(\x0e\x32\x18.lth.egm.Header.EGM_Mode:\x14MODE_POSITION_STREAM\"R\n\x0bMessageType\x12\x15\n\x11MSGTYPE_UNDEFINED\x10\x00\x12\x17\n\x13MSGTYPE_POS_COMMAND\x10\x01\x12\x13\n\x0fMSGTYPE_POS_ACK\x10\x02\"Z\n\x08\x45GM_Mode\x12\x18\n\x14MODE_POSITION_STREAM\x10\x00\x12\x1a\n\x16MODE_POSITION_GUIDANCE\x10\x01\x12\x18\n\x14MODE_PATH_CORRECTION\x10\x02\"+\n\x08Position\x12\t\n\x01x\x18\x01 \x02(\x01\x12\t\n\x01y\x18\x02 \x02(\x01\x12\t\n\x01z\x18\x03 \x02(\x01\"S\n\x0b\x45GM_Control\x12\x1f\n\x06header\x18\x01 \x02(\x0b\x32\x0f.lth.egm.Header\x12#\n\x08position\x18\x02 \x02(\x0b\x32\x11.lth.egm.Position')



_HEADER_MESSAGETYPE = descriptor.EnumDescriptor(
  name='MessageType',
  full_name='lth.egm.Header.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='MSGTYPE_UNDEFINED', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSGTYPE_POS_COMMAND', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MSGTYPE_POS_ACK', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=189,
  serialized_end=271,
)

_HEADER_EGM_MODE = descriptor.EnumDescriptor(
  name='EGM_Mode',
  full_name='lth.egm.Header.EGM_Mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='MODE_POSITION_STREAM', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MODE_POSITION_GUIDANCE', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MODE_PATH_CORRECTION', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=273,
  serialized_end=363,
)


_HEADER = descriptor.Descriptor(
  name='Header',
  full_name='lth.egm.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='seqno', full_name='lth.egm.Header.seqno', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='tm', full_name='lth.egm.Header.tm', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mtype', full_name='lth.egm.Header.mtype', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='mode', full_name='lth.egm.Header.mode', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _HEADER_MESSAGETYPE,
    _HEADER_EGM_MODE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=363,
)


_POSITION = descriptor.Descriptor(
  name='Position',
  full_name='lth.egm.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='x', full_name='lth.egm.Position.x', index=0,
      number=1, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='y', full_name='lth.egm.Position.y', index=1,
      number=2, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='z', full_name='lth.egm.Position.z', index=2,
      number=3, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=365,
  serialized_end=408,
)


_EGM_CONTROL = descriptor.Descriptor(
  name='EGM_Control',
  full_name='lth.egm.EGM_Control',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='header', full_name='lth.egm.EGM_Control.header', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='position', full_name='lth.egm.EGM_Control.position', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=410,
  serialized_end=493,
)

_HEADER.fields_by_name['mtype'].enum_type = _HEADER_MESSAGETYPE
_HEADER.fields_by_name['mode'].enum_type = _HEADER_EGM_MODE
_HEADER_MESSAGETYPE.containing_type = _HEADER;
_HEADER_EGM_MODE.containing_type = _HEADER;
_EGM_CONTROL.fields_by_name['header'].message_type = _HEADER
_EGM_CONTROL.fields_by_name['position'].message_type = _POSITION
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['EGM_Control'] = _EGM_CONTROL

class Header(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEADER
  
  # @@protoc_insertion_point(class_scope:lth.egm.Header)

class Position(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POSITION
  
  # @@protoc_insertion_point(class_scope:lth.egm.Position)

class EGM_Control(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EGM_CONTROL
  
  # @@protoc_insertion_point(class_scope:lth.egm.EGM_Control)

# @@protoc_insertion_point(module_scope)
