// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lth_egm.proto

package lth.egm;

public final class LthEgm {
  private LthEgm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional uint32 seqno = 1;
    boolean hasSeqno();
    int getSeqno();
    
    // optional uint32 tm = 2;
    boolean hasTm();
    int getTm();
    
    // optional .lth.egm.Header.MessageType mtype = 3 [default = MSGTYPE_UNDEFINED];
    boolean hasMtype();
    lth.egm.LthEgm.Header.MessageType getMtype();
    
    // optional .lth.egm.Header.EGM_Mode mode = 4 [default = MODE_POSITION_STREAM];
    boolean hasMode();
    lth.egm.LthEgm.Header.EGM_Mode getMode();
  }
  public static final class Header extends
      com.google.protobuf.GeneratedMessage
      implements HeaderOrBuilder {
    // Use Header.newBuilder() to construct.
    private Header(Builder builder) {
      super(builder);
    }
    private Header(boolean noInit) {}
    
    private static final Header defaultInstance;
    public static Header getDefaultInstance() {
      return defaultInstance;
    }
    
    public Header getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lth.egm.LthEgm.internal_static_lth_egm_Header_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lth.egm.LthEgm.internal_static_lth_egm_Header_fieldAccessorTable;
    }
    
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      MSGTYPE_UNDEFINED(0, 0),
      MSGTYPE_POS_COMMAND(1, 1),
      MSGTYPE_POS_ACK(2, 2),
      ;
      
      public static final int MSGTYPE_UNDEFINED_VALUE = 0;
      public static final int MSGTYPE_POS_COMMAND_VALUE = 1;
      public static final int MSGTYPE_POS_ACK_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static MessageType valueOf(int value) {
        switch (value) {
          case 0: return MSGTYPE_UNDEFINED;
          case 1: return MSGTYPE_POS_COMMAND;
          case 2: return MSGTYPE_POS_ACK;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return lth.egm.LthEgm.Header.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final MessageType[] VALUES = {
        MSGTYPE_UNDEFINED, MSGTYPE_POS_COMMAND, MSGTYPE_POS_ACK, 
      };
      
      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:lth.egm.Header.MessageType)
    }
    
    public enum EGM_Mode
        implements com.google.protobuf.ProtocolMessageEnum {
      MODE_POSITION_STREAM(0, 0),
      MODE_POSITION_GUIDANCE(1, 1),
      MODE_PATH_CORRECTION(2, 2),
      ;
      
      public static final int MODE_POSITION_STREAM_VALUE = 0;
      public static final int MODE_POSITION_GUIDANCE_VALUE = 1;
      public static final int MODE_PATH_CORRECTION_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static EGM_Mode valueOf(int value) {
        switch (value) {
          case 0: return MODE_POSITION_STREAM;
          case 1: return MODE_POSITION_GUIDANCE;
          case 2: return MODE_PATH_CORRECTION;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<EGM_Mode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EGM_Mode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EGM_Mode>() {
              public EGM_Mode findValueByNumber(int number) {
                return EGM_Mode.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return lth.egm.LthEgm.Header.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final EGM_Mode[] VALUES = {
        MODE_POSITION_STREAM, MODE_POSITION_GUIDANCE, MODE_PATH_CORRECTION, 
      };
      
      public static EGM_Mode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private EGM_Mode(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:lth.egm.Header.EGM_Mode)
    }
    
    private int bitField0_;
    // optional uint32 seqno = 1;
    public static final int SEQNO_FIELD_NUMBER = 1;
    private int seqno_;
    public boolean hasSeqno() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getSeqno() {
      return seqno_;
    }
    
    // optional uint32 tm = 2;
    public static final int TM_FIELD_NUMBER = 2;
    private int tm_;
    public boolean hasTm() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getTm() {
      return tm_;
    }
    
    // optional .lth.egm.Header.MessageType mtype = 3 [default = MSGTYPE_UNDEFINED];
    public static final int MTYPE_FIELD_NUMBER = 3;
    private lth.egm.LthEgm.Header.MessageType mtype_;
    public boolean hasMtype() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public lth.egm.LthEgm.Header.MessageType getMtype() {
      return mtype_;
    }
    
    // optional .lth.egm.Header.EGM_Mode mode = 4 [default = MODE_POSITION_STREAM];
    public static final int MODE_FIELD_NUMBER = 4;
    private lth.egm.LthEgm.Header.EGM_Mode mode_;
    public boolean hasMode() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public lth.egm.LthEgm.Header.EGM_Mode getMode() {
      return mode_;
    }
    
    private void initFields() {
      seqno_ = 0;
      tm_ = 0;
      mtype_ = lth.egm.LthEgm.Header.MessageType.MSGTYPE_UNDEFINED;
      mode_ = lth.egm.LthEgm.Header.EGM_Mode.MODE_POSITION_STREAM;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, seqno_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, tm_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, mtype_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(4, mode_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, seqno_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, tm_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, mtype_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, mode_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static lth.egm.LthEgm.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static lth.egm.LthEgm.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static lth.egm.LthEgm.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static lth.egm.LthEgm.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static lth.egm.LthEgm.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static lth.egm.LthEgm.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static lth.egm.LthEgm.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static lth.egm.LthEgm.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static lth.egm.LthEgm.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static lth.egm.LthEgm.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(lth.egm.LthEgm.Header prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements lth.egm.LthEgm.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lth.egm.LthEgm.internal_static_lth_egm_Header_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lth.egm.LthEgm.internal_static_lth_egm_Header_fieldAccessorTable;
      }
      
      // Construct using lth.egm.LthEgm.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        seqno_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        tm_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        mtype_ = lth.egm.LthEgm.Header.MessageType.MSGTYPE_UNDEFINED;
        bitField0_ = (bitField0_ & ~0x00000004);
        mode_ = lth.egm.LthEgm.Header.EGM_Mode.MODE_POSITION_STREAM;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lth.egm.LthEgm.Header.getDescriptor();
      }
      
      public lth.egm.LthEgm.Header getDefaultInstanceForType() {
        return lth.egm.LthEgm.Header.getDefaultInstance();
      }
      
      public lth.egm.LthEgm.Header build() {
        lth.egm.LthEgm.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private lth.egm.LthEgm.Header buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        lth.egm.LthEgm.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public lth.egm.LthEgm.Header buildPartial() {
        lth.egm.LthEgm.Header result = new lth.egm.LthEgm.Header(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.seqno_ = seqno_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tm_ = tm_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mtype_ = mtype_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mode_ = mode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lth.egm.LthEgm.Header) {
          return mergeFrom((lth.egm.LthEgm.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(lth.egm.LthEgm.Header other) {
        if (other == lth.egm.LthEgm.Header.getDefaultInstance()) return this;
        if (other.hasSeqno()) {
          setSeqno(other.getSeqno());
        }
        if (other.hasTm()) {
          setTm(other.getTm());
        }
        if (other.hasMtype()) {
          setMtype(other.getMtype());
        }
        if (other.hasMode()) {
          setMode(other.getMode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              seqno_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              tm_ = input.readUInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              lth.egm.LthEgm.Header.MessageType value = lth.egm.LthEgm.Header.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                mtype_ = value;
              }
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              lth.egm.LthEgm.Header.EGM_Mode value = lth.egm.LthEgm.Header.EGM_Mode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                mode_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 seqno = 1;
      private int seqno_ ;
      public boolean hasSeqno() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getSeqno() {
        return seqno_;
      }
      public Builder setSeqno(int value) {
        bitField0_ |= 0x00000001;
        seqno_ = value;
        onChanged();
        return this;
      }
      public Builder clearSeqno() {
        bitField0_ = (bitField0_ & ~0x00000001);
        seqno_ = 0;
        onChanged();
        return this;
      }
      
      // optional uint32 tm = 2;
      private int tm_ ;
      public boolean hasTm() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getTm() {
        return tm_;
      }
      public Builder setTm(int value) {
        bitField0_ |= 0x00000002;
        tm_ = value;
        onChanged();
        return this;
      }
      public Builder clearTm() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tm_ = 0;
        onChanged();
        return this;
      }
      
      // optional .lth.egm.Header.MessageType mtype = 3 [default = MSGTYPE_UNDEFINED];
      private lth.egm.LthEgm.Header.MessageType mtype_ = lth.egm.LthEgm.Header.MessageType.MSGTYPE_UNDEFINED;
      public boolean hasMtype() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public lth.egm.LthEgm.Header.MessageType getMtype() {
        return mtype_;
      }
      public Builder setMtype(lth.egm.LthEgm.Header.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        mtype_ = value;
        onChanged();
        return this;
      }
      public Builder clearMtype() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mtype_ = lth.egm.LthEgm.Header.MessageType.MSGTYPE_UNDEFINED;
        onChanged();
        return this;
      }
      
      // optional .lth.egm.Header.EGM_Mode mode = 4 [default = MODE_POSITION_STREAM];
      private lth.egm.LthEgm.Header.EGM_Mode mode_ = lth.egm.LthEgm.Header.EGM_Mode.MODE_POSITION_STREAM;
      public boolean hasMode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public lth.egm.LthEgm.Header.EGM_Mode getMode() {
        return mode_;
      }
      public Builder setMode(lth.egm.LthEgm.Header.EGM_Mode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        mode_ = value;
        onChanged();
        return this;
      }
      public Builder clearMode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mode_ = lth.egm.LthEgm.Header.EGM_Mode.MODE_POSITION_STREAM;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:lth.egm.Header)
    }
    
    static {
      defaultInstance = new Header(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:lth.egm.Header)
  }
  
  public interface PositionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required double x = 1;
    boolean hasX();
    double getX();
    
    // required double y = 2;
    boolean hasY();
    double getY();
    
    // required double z = 3;
    boolean hasZ();
    double getZ();
  }
  public static final class Position extends
      com.google.protobuf.GeneratedMessage
      implements PositionOrBuilder {
    // Use Position.newBuilder() to construct.
    private Position(Builder builder) {
      super(builder);
    }
    private Position(boolean noInit) {}
    
    private static final Position defaultInstance;
    public static Position getDefaultInstance() {
      return defaultInstance;
    }
    
    public Position getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lth.egm.LthEgm.internal_static_lth_egm_Position_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lth.egm.LthEgm.internal_static_lth_egm_Position_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required double x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private double x_;
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public double getX() {
      return x_;
    }
    
    // required double y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private double y_;
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getY() {
      return y_;
    }
    
    // required double z = 3;
    public static final int Z_FIELD_NUMBER = 3;
    private double z_;
    public boolean hasZ() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public double getZ() {
      return z_;
    }
    
    private void initFields() {
      x_ = 0D;
      y_ = 0D;
      z_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZ()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, z_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, z_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static lth.egm.LthEgm.Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static lth.egm.LthEgm.Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static lth.egm.LthEgm.Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static lth.egm.LthEgm.Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static lth.egm.LthEgm.Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static lth.egm.LthEgm.Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static lth.egm.LthEgm.Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static lth.egm.LthEgm.Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static lth.egm.LthEgm.Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static lth.egm.LthEgm.Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(lth.egm.LthEgm.Position prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements lth.egm.LthEgm.PositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lth.egm.LthEgm.internal_static_lth_egm_Position_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lth.egm.LthEgm.internal_static_lth_egm_Position_fieldAccessorTable;
      }
      
      // Construct using lth.egm.LthEgm.Position.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        x_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        z_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lth.egm.LthEgm.Position.getDescriptor();
      }
      
      public lth.egm.LthEgm.Position getDefaultInstanceForType() {
        return lth.egm.LthEgm.Position.getDefaultInstance();
      }
      
      public lth.egm.LthEgm.Position build() {
        lth.egm.LthEgm.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private lth.egm.LthEgm.Position buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        lth.egm.LthEgm.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public lth.egm.LthEgm.Position buildPartial() {
        lth.egm.LthEgm.Position result = new lth.egm.LthEgm.Position(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.z_ = z_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lth.egm.LthEgm.Position) {
          return mergeFrom((lth.egm.LthEgm.Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(lth.egm.LthEgm.Position other) {
        if (other == lth.egm.LthEgm.Position.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasZ()) {
          setZ(other.getZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasZ()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              x_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              y_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              z_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required double x = 1;
      private double x_ ;
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public double getX() {
        return x_;
      }
      public Builder setX(double value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        onChanged();
        return this;
      }
      
      // required double y = 2;
      private double y_ ;
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getY() {
        return y_;
      }
      public Builder setY(double value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        onChanged();
        return this;
      }
      
      // required double z = 3;
      private double z_ ;
      public boolean hasZ() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getZ() {
        return z_;
      }
      public Builder setZ(double value) {
        bitField0_ |= 0x00000004;
        z_ = value;
        onChanged();
        return this;
      }
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000004);
        z_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:lth.egm.Position)
    }
    
    static {
      defaultInstance = new Position(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:lth.egm.Position)
  }
  
  public interface EGM_ControlOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .lth.egm.Header header = 1;
    boolean hasHeader();
    lth.egm.LthEgm.Header getHeader();
    lth.egm.LthEgm.HeaderOrBuilder getHeaderOrBuilder();
    
    // required .lth.egm.Position position = 2;
    boolean hasPosition();
    lth.egm.LthEgm.Position getPosition();
    lth.egm.LthEgm.PositionOrBuilder getPositionOrBuilder();
  }
  public static final class EGM_Control extends
      com.google.protobuf.GeneratedMessage
      implements EGM_ControlOrBuilder {
    // Use EGM_Control.newBuilder() to construct.
    private EGM_Control(Builder builder) {
      super(builder);
    }
    private EGM_Control(boolean noInit) {}
    
    private static final EGM_Control defaultInstance;
    public static EGM_Control getDefaultInstance() {
      return defaultInstance;
    }
    
    public EGM_Control getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return lth.egm.LthEgm.internal_static_lth_egm_EGM_Control_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return lth.egm.LthEgm.internal_static_lth_egm_EGM_Control_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .lth.egm.Header header = 1;
    public static final int HEADER_FIELD_NUMBER = 1;
    private lth.egm.LthEgm.Header header_;
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public lth.egm.LthEgm.Header getHeader() {
      return header_;
    }
    public lth.egm.LthEgm.HeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }
    
    // required .lth.egm.Position position = 2;
    public static final int POSITION_FIELD_NUMBER = 2;
    private lth.egm.LthEgm.Position position_;
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public lth.egm.LthEgm.Position getPosition() {
      return position_;
    }
    public lth.egm.LthEgm.PositionOrBuilder getPositionOrBuilder() {
      return position_;
    }
    
    private void initFields() {
      header_ = lth.egm.LthEgm.Header.getDefaultInstance();
      position_ = lth.egm.LthEgm.Position.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPosition()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getPosition().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, position_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, position_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static lth.egm.LthEgm.EGM_Control parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static lth.egm.LthEgm.EGM_Control parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static lth.egm.LthEgm.EGM_Control parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static lth.egm.LthEgm.EGM_Control parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static lth.egm.LthEgm.EGM_Control parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static lth.egm.LthEgm.EGM_Control parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static lth.egm.LthEgm.EGM_Control parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static lth.egm.LthEgm.EGM_Control parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static lth.egm.LthEgm.EGM_Control parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static lth.egm.LthEgm.EGM_Control parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(lth.egm.LthEgm.EGM_Control prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements lth.egm.LthEgm.EGM_ControlOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return lth.egm.LthEgm.internal_static_lth_egm_EGM_Control_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return lth.egm.LthEgm.internal_static_lth_egm_EGM_Control_fieldAccessorTable;
      }
      
      // Construct using lth.egm.LthEgm.EGM_Control.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
          getPositionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = lth.egm.LthEgm.Header.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (positionBuilder_ == null) {
          position_ = lth.egm.LthEgm.Position.getDefaultInstance();
        } else {
          positionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return lth.egm.LthEgm.EGM_Control.getDescriptor();
      }
      
      public lth.egm.LthEgm.EGM_Control getDefaultInstanceForType() {
        return lth.egm.LthEgm.EGM_Control.getDefaultInstance();
      }
      
      public lth.egm.LthEgm.EGM_Control build() {
        lth.egm.LthEgm.EGM_Control result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private lth.egm.LthEgm.EGM_Control buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        lth.egm.LthEgm.EGM_Control result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public lth.egm.LthEgm.EGM_Control buildPartial() {
        lth.egm.LthEgm.EGM_Control result = new lth.egm.LthEgm.EGM_Control(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (positionBuilder_ == null) {
          result.position_ = position_;
        } else {
          result.position_ = positionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof lth.egm.LthEgm.EGM_Control) {
          return mergeFrom((lth.egm.LthEgm.EGM_Control)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(lth.egm.LthEgm.EGM_Control other) {
        if (other == lth.egm.LthEgm.EGM_Control.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasHeader()) {
          
          return false;
        }
        if (!hasPosition()) {
          
          return false;
        }
        if (!getPosition().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              lth.egm.LthEgm.Header.Builder subBuilder = lth.egm.LthEgm.Header.newBuilder();
              if (hasHeader()) {
                subBuilder.mergeFrom(getHeader());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHeader(subBuilder.buildPartial());
              break;
            }
            case 18: {
              lth.egm.LthEgm.Position.Builder subBuilder = lth.egm.LthEgm.Position.newBuilder();
              if (hasPosition()) {
                subBuilder.mergeFrom(getPosition());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPosition(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .lth.egm.Header header = 1;
      private lth.egm.LthEgm.Header header_ = lth.egm.LthEgm.Header.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          lth.egm.LthEgm.Header, lth.egm.LthEgm.Header.Builder, lth.egm.LthEgm.HeaderOrBuilder> headerBuilder_;
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public lth.egm.LthEgm.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      public Builder setHeader(lth.egm.LthEgm.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setHeader(
          lth.egm.LthEgm.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeHeader(lth.egm.LthEgm.Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != lth.egm.LthEgm.Header.getDefaultInstance()) {
            header_ =
              lth.egm.LthEgm.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = lth.egm.LthEgm.Header.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public lth.egm.LthEgm.Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      public lth.egm.LthEgm.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          lth.egm.LthEgm.Header, lth.egm.LthEgm.Header.Builder, lth.egm.LthEgm.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              lth.egm.LthEgm.Header, lth.egm.LthEgm.Header.Builder, lth.egm.LthEgm.HeaderOrBuilder>(
                  header_,
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }
      
      // required .lth.egm.Position position = 2;
      private lth.egm.LthEgm.Position position_ = lth.egm.LthEgm.Position.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          lth.egm.LthEgm.Position, lth.egm.LthEgm.Position.Builder, lth.egm.LthEgm.PositionOrBuilder> positionBuilder_;
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public lth.egm.LthEgm.Position getPosition() {
        if (positionBuilder_ == null) {
          return position_;
        } else {
          return positionBuilder_.getMessage();
        }
      }
      public Builder setPosition(lth.egm.LthEgm.Position value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          position_ = value;
          onChanged();
        } else {
          positionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setPosition(
          lth.egm.LthEgm.Position.Builder builderForValue) {
        if (positionBuilder_ == null) {
          position_ = builderForValue.build();
          onChanged();
        } else {
          positionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergePosition(lth.egm.LthEgm.Position value) {
        if (positionBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              position_ != lth.egm.LthEgm.Position.getDefaultInstance()) {
            position_ =
              lth.egm.LthEgm.Position.newBuilder(position_).mergeFrom(value).buildPartial();
          } else {
            position_ = value;
          }
          onChanged();
        } else {
          positionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearPosition() {
        if (positionBuilder_ == null) {
          position_ = lth.egm.LthEgm.Position.getDefaultInstance();
          onChanged();
        } else {
          positionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public lth.egm.LthEgm.Position.Builder getPositionBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPositionFieldBuilder().getBuilder();
      }
      public lth.egm.LthEgm.PositionOrBuilder getPositionOrBuilder() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilder();
        } else {
          return position_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          lth.egm.LthEgm.Position, lth.egm.LthEgm.Position.Builder, lth.egm.LthEgm.PositionOrBuilder> 
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              lth.egm.LthEgm.Position, lth.egm.LthEgm.Position.Builder, lth.egm.LthEgm.PositionOrBuilder>(
                  position_,
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:lth.egm.EGM_Control)
    }
    
    static {
      defaultInstance = new EGM_Control(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:lth.egm.EGM_Control)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_lth_egm_Header_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lth_egm_Header_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_lth_egm_Position_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lth_egm_Position_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_lth_egm_EGM_Control_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_lth_egm_EGM_Control_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rlth_egm.proto\022\007lth.egm\"\320\002\n\006Header\022\r\n\005s" +
      "eqno\030\001 \001(\r\022\n\n\002tm\030\002 \001(\r\022=\n\005mtype\030\003 \001(\0162\033." +
      "lth.egm.Header.MessageType:\021MSGTYPE_UNDE" +
      "FINED\022<\n\004mode\030\004 \001(\0162\030.lth.egm.Header.EGM" +
      "_Mode:\024MODE_POSITION_STREAM\"R\n\013MessageTy" +
      "pe\022\025\n\021MSGTYPE_UNDEFINED\020\000\022\027\n\023MSGTYPE_POS" +
      "_COMMAND\020\001\022\023\n\017MSGTYPE_POS_ACK\020\002\"Z\n\010EGM_M" +
      "ode\022\030\n\024MODE_POSITION_STREAM\020\000\022\032\n\026MODE_PO" +
      "SITION_GUIDANCE\020\001\022\030\n\024MODE_PATH_CORRECTIO" +
      "N\020\002\"+\n\010Position\022\t\n\001x\030\001 \002(\001\022\t\n\001y\030\002 \002(\001\022\t\n",
      "\001z\030\003 \002(\001\"S\n\013EGM_Control\022\037\n\006header\030\001 \002(\0132" +
      "\017.lth.egm.Header\022#\n\010position\030\002 \002(\0132\021.lth" +
      ".egm.Position"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_lth_egm_Header_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_lth_egm_Header_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_lth_egm_Header_descriptor,
              new java.lang.String[] { "Seqno", "Tm", "Mtype", "Mode", },
              lth.egm.LthEgm.Header.class,
              lth.egm.LthEgm.Header.Builder.class);
          internal_static_lth_egm_Position_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_lth_egm_Position_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_lth_egm_Position_descriptor,
              new java.lang.String[] { "X", "Y", "Z", },
              lth.egm.LthEgm.Position.class,
              lth.egm.LthEgm.Position.Builder.class);
          internal_static_lth_egm_EGM_Control_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_lth_egm_EGM_Control_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_lth_egm_EGM_Control_descriptor,
              new java.lang.String[] { "Header", "Position", },
              lth.egm.LthEgm.EGM_Control.class,
              lth.egm.LthEgm.EGM_Control.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
